option(RASMOL_AUTO_INSTALL "Automatically install missing dependencies" OFF)

if(RASMOL_AUTO_INSTALL)
    set(NEEDS_INSTALL FALSE)

    # Check for Bison 2.7+
    find_package(BISON 2.7 QUIET)
    if(NOT BISON_FOUND)
        set(NEEDS_INSTALL TRUE)
        message(STATUS "Bison 2.7+ not found.")
    endif()

    # Check for Tcl/Tk
    if(NOT NEEDS_INSTALL)
        find_package(TCL QUIET)
        find_package(TK QUIET)
        if(NOT TCL_FOUND OR NOT TK_FOUND)
            if(NOT WIN32)
                set(NEEDS_INSTALL TRUE)
                message(STATUS "Tcl/Tk not found.")
            endif()
        endif()
    endif()

    # Check for HDF5
    if(NOT NEEDS_INSTALL)
        if(APPLE)
            find_path(HDF5_INCLUDE_DIR hdf5.h PATHS /opt/local/include /opt/homebrew/opt/hdf5/include /usr/local/opt/hdf5/include QUIET)
            if(NOT HDF5_INCLUDE_DIR)
                set(NEEDS_INSTALL TRUE)
                message(STATUS "HDF5 not found.")
            endif()
        else()
            find_package(HDF5 QUIET COMPONENTS C)
            if(NOT HDF5_FOUND)
                find_path(HDF5_INCLUDE_DIR hdf5.h PATH_SUFFIXES hdf5/serial QUIET)
                if(NOT HDF5_INCLUDE_DIR)
                    set(NEEDS_INSTALL TRUE)
                    message(STATUS "HDF5 not found.")
                endif()
            endif()
        endif()
    endif()

    if(NEEDS_INSTALL)
        message(STATUS "Dependencies missing, attempting auto-installation...")
        if(APPLE)
            message(STATUS "Installing dependencies via MacPorts...")
            execute_process(COMMAND sudo port selfupdate)
            set(PORT_ARGS "")
            if(CMAKE_OSX_ARCHITECTURES)
                list(GET CMAKE_OSX_ARCHITECTURES 0 ARCH)
                set(PORT_ARGS "configure.build_arch=${ARCH}" "configure.universal_archs=${ARCH}")
            endif()
            execute_process(COMMAND sudo port install bison)
            execute_process(COMMAND sudo port install tcl tk libjpeg-turbo hdf5 zstd webp lerc libdeflate jbigkit xz zlib ${PORT_ARGS})
        elseif(UNIX AND NOT APPLE)
            message(STATUS "Installing dependencies via apt...")
            execute_process(COMMAND sudo apt-get update)
            execute_process(COMMAND sudo apt-get install -y rpm libx11-dev libxext-dev libxi-dev libhdf5-dev tcl-dev tk-dev bison libxpm-dev libdeflate-dev libjbig-dev liblerc-dev libwebp-dev libjpeg-dev imagemagick)
        elseif(WIN32)
            message(STATUS "Installing dependencies via Chocolatey and dotnet...")
            execute_process(COMMAND choco --version RESULT_VARIABLE CHOCO_CHECK OUTPUT_QUIET ERROR_QUIET)
            if(CHOCO_CHECK EQUAL 0)
                execute_process(COMMAND choco install magicsplat-tcl-tk --version=1.16.0 -y)
            else()
                message(WARNING "Chocolatey not found. Cannot install Tcl/Tk automatically.")
            endif()

            execute_process(COMMAND dotnet --version RESULT_VARIABLE DOTNET_CHECK OUTPUT_QUIET ERROR_QUIET)
            if(DOTNET_CHECK EQUAL 0)
                execute_process(COMMAND wix --version RESULT_VARIABLE WIX_CHECK OUTPUT_QUIET ERROR_QUIET)
                if(NOT WIX_CHECK EQUAL 0)
                    execute_process(COMMAND dotnet tool install --global WiX)
                endif()
            else()
                message(WARNING "dotnet not found. Cannot install WiX automatically.")
            endif()
        endif()
    else()
        message(STATUS "All basic dependencies found. Skipping auto-installation.")
    endif()
endif()
