# RasMol Tcl/Tk Localization Data and Logic

array set ui_translations {
    "Bulgarian" {
        "File" "Файл"
        "Open" "Отвори..."
        "Info" "Информация"
        "Close" "Затвори"
        "Exit" "Изход"
        "Display" "Визуализация"
        "Wireframe" "Мрежест модел"
        "Backbone" "Гръбнак"
        "Sticks" "Пръчки"
        "Spacefill" "Запълване на пространството"
        "BallStick" "Топки и пръчки"
        "Ribbons" "Ленти"
        "Strands" "Нишки"
        "Cartoons" "Схематичен модел"
        "MolSurf" "Молекулна повърхност"
        "Colours" "Цветове"
        "Monochrome" "Едноцветен"
        "CPK" "CPK"
        "Shapely" "По форма"
        "Group" "Група"
        "Chain" "Верига"
        "Temp" "Температура"
        "Struct" "Структура"
        "User" "Потребител"
        "Model" "Модел"
        "Alt" "Алтернативен"
        "Options" "Опции"
        "Slab" "Срез"
        "Hydr" "Водородни атоми"
        "Het" "Хетероатоми"
        "Spec" "Огледален"
        "Shad" "Сенки"
        "Stereo" "Стерео"
        "Label" "Етикети"
        "Settings" "Настройки"
        "POff" "Изключи маркирането"
        "PIdent" "Идентифициране"
        "PDist" "Разстояние"
        "PMon" "Монитор"
        "PAng" "Ъгъл"
        "PTrsn" "Торзионен ъгъл"
        "PLabl" "Етикет"
        "PCent" "Център"
        "PCoord" "Координати"
        "PBond" "Връзка"
        "RBond" "Ротация на връзка"
        "RMol" "Ротация на молекула"
        "RAll" "Ротация на всичко"
        "Export" "Експорт"
        "Help" "Помощ"
        "About" "Относно RasMol..."
        "UserM" "Ръководство..."
    }
    "English" {
        "File" "File"
        "Open" "Open"
        "Info" "Information"
        "Close" "Close"
        "Exit" "Exit"
        "Display" "Display"
        "Wireframe" "Wireframe"
        "Backbone" "Backbone"
        "Sticks" "Sticks"
        "Spacefill" "Spacefill"
        "BallStick" "Ball & Stick"
        "Ribbons" "Ribbons"
        "Strands" "Strands"
        "Cartoons" "Cartoons"
        "MolSurf" "Molecular Surface"
        "Colours" "Colours"
        "Monochrome" "Monochrome"
        "CPK" "CPK"
        "Shapely" "Shapely"
        "Group" "Group"
        "Chain" "Chain"
        "Temp" "Temperature"
        "Struct" "Structure"
        "User" "User"
        "Model" "Model"
        "Alt" "Alt"
        "Options" "Options"
        "Slab" "Slab Mode"
        "Hydr" "Hydrogens"
        "Het" "Hetero Atoms"
        "Spec" "Specular"
        "Shad" "Shadows"
        "Stereo" "Stereo"
        "Label" "Labels"
        "Settings" "Settings"
        "POff" "Pick Off"
        "PIdent" "Pick Ident"
        "PDist" "Pick Distance"
        "PMon" "Pick Monitor"
        "PAng" "Pick Angle"
        "PTrsn" "Pick Torsion"
        "PLabl" "Pick Label"
        "PCent" "Pick Centre"
        "PCoord" "Pick Coord"
        "PBond" "Pick Bond"
        "RBond" "Rotate Bond"
        "RMol" "Rotate Molecule"
        "RAll" "Rotate All"
        "Export" "Export"
        "Help" "Help"
        "About" "About RasMol"
        "UserM" "User Manual"
    }
    "French" {
        "File" "Fichier"
        "Open" "Ouvrir..."
        "Info" "Information"
        "Close" "Fermer"
        "Exit" "Quitter"
        "Display" "Affichage"
        "Wireframe" "Fil de fer"
        "Backbone" "Squelette"
        "Sticks" "Bâtonnets"
        "Spacefill" "Sphères"
        "BallStick" "Boules & Bâtonnets"
        "Ribbons" "Rubans"
        "Strands" "Brins"
        "Cartoons" "Schématique"
        "MolSurf" "Surface moléculaire"
        "Colours" "Couleurs"
        "Monochrome" "Monochrome"
        "CPK" "CPK"
        "Shapely" "Forme"
        "Group" "Groupe"
        "Chain" "Chaîne"
        "Temp" "Température"
        "Struct" "Structure"
        "User" "Utilisateur"
        "Model" "Modèle"
        "Alt" "Alt"
        "Options" "Options"
        "Slab" "Mode coupe"
        "Hydr" "Hydrogènes"
        "Het" "Hétéroatomes"
        "Spec" "Spéculaire"
        "Shad" "Ombres"
        "Stereo" "Stéréo"
        "Label" "Etiquettes"
        "Settings" "Réglages"
        "POff" "Désactiver sélection"
        "PIdent" "Identifier"
        "PDist" "Distance"
        "PMon" "Moniteur"
        "PAng" "Angle"
        "PTrsn" "Torsion"
        "PLabl" "Etiquette"
        "PCent" "Centrer"
        "PCoord" "Coordonnées"
        "PBond" "Liaison"
        "RBond" "Rotation liaison"
        "RMol" "Rotation molécule"
        "RAll" "Rotation globale"
        "Export" "Exporter"
        "Help" "Aide"
        "About" "A propos de RasMol..."
        "UserM" "Manuel utilisateur..."
    }
    "Italian" {
        "File" "File"
        "Open" "Apri..."
        "Info" "Informazioni"
        "Close" "Chiudi"
        "Exit" "Esci"
        "Display" "Visualizza"
        "Wireframe" "Filo di ferro"
        "Backbone" "Scheletro"
        "Sticks" "Bastoncini"
        "Spacefill" "Sfere"
        "BallStick" "Palle & Bastoncini"
        "Ribbons" "Nastri"
        "Strands" "Fibre"
        "Cartoons" "Fumetti"
        "MolSurf" "Superficie molecolare"
        "Colours" "Colori"
        "Monochrome" "Monocromo"
        "CPK" "CPK"
        "Shapely" "Forma"
        "Group" "Gruppo"
        "Chain" "Catena"
        "Temp" "Temperatura"
        "Struct" "Struttura"
        "User" "Utente"
        "Model" "Modello"
        "Alt" "Alt"
        "Options" "Opzioni"
        "Slab" "Modo sezione"
        "Hydr" "Idrogeni"
        "Het" "Eteroatomi"
        "Spec" "Speculare"
        "Shad" "Ombre"
        "Stereo" "Stereo"
        "Label" "Etichette"
        "Settings" "Impostazioni"
        "POff" "Disattiva scelta"
        "PIdent" "Identifica"
        "PDist" "Distanza"
        "PMon" "Monitor"
        "PAng" "Angolo"
        "PTrsn" "Torsione"
        "PLabl" "Etichetta"
        "PCent" "Centra"
        "PCoord" "Coordinate"
        "PBond" "Legame"
        "RBond" "Ruota legame"
        "RMol" "Ruota molecola"
        "RAll" "Ruota tutto"
        "Export" "Esporta"
        "Help" "Aiuto"
        "About" "Informazioni su RasMol..."
        "UserM" "Manuale Utente..."
    }
    "Japanese" {
        "File" "ファイル"
        "Open" "開く..."
        "Info" "情報"
        "Close" "閉じる"
        "Exit" "終了"
        "Display" "表示方法"
        "Wireframe" "ワイヤーフレーム"
        "Backbone" "主鎖"
        "Sticks" "スティック"
        "Spacefill" "空間充填モデル"
        "BallStick" "球棒"
        "Ribbons" "リボン"
        "Strands" "ストランド"
        "Cartoons" "カートゥーン"
        "MolSurf" "分子表面"
        "Colours" "色"
        "Monochrome" "白黒"
        "CPK" "CPKカラー"
        "Shapely" "型"
        "Group" "グループ"
        "Chain" "鎖"
        "Temp" "温度"
        "Struct" "構造"
        "User" "ユーザー"
        "Model" "モデル"
        "Alt" "換構造"
        "Options" "オプション"
        "Slab" "スラブモード"
        "Hydr" "水素原子"
        "Het" "ヘテロ原子"
        "Spec" "輝き"
        "Shad" "影"
        "Stereo" "ステレオ"
        "Label" "ラベル"
        "Settings" "設定"
        "POff" "オフ"
        "PIdent" "選択されたものを表示"
        "PDist" "距離を計る"
        "PMon" "距離を表示"
        "PAng" "角度を計る"
        "PTrsn" "二面角をはかる"
        "PLabl" "ラベルを付ける"
        "PCent" "中心を設定"
        "PCoord" "座標を表示"
        "PBond" "結合を指定"
        "RBond" "結合を回転"
        "RMol" "分子を回転"
        "RAll" "すべてを回転"
        "Export" "画像出力"
        "Help" "ヘルプ"
        "About" "RasMolについて..."
        "UserM" "マニュアル..."
    }
    "Russian" {
        "File" "Файл"
        "Open" "Открыть..."
        "Info" "Информация"
        "Close" "Закрыть"
        "Exit" "Выход"
        "Display" "Отображение"
        "Wireframe" "Проволочный"
        "Backbone" "Остов"
        "Sticks" "Палочки"
        "Spacefill" "Сферы"
        "BallStick" "Шаростержневой"
        "Ribbons" "Ленты"
        "Strands" "Нити"
        "Cartoons" "Схематичный"
        "MolSurf" "Молекулярная поверхность"
        "Colours" "Цвета"
        "Monochrome" "Одноцветный"
        "CPK" "CPK"
        "Shapely" "Фигурный"
        "Group" "Группа"
        "Chain" "Цепь"
        "Temp" "Температура"
        "Struct" "Структура"
        "User" "Пользователь"
        "Model" "Модель"
        "Alt" "Alt"
        "Options" "Опции"
        "Slab" "Плоскость сечения"
        "Hydr" "Водороды"
        "Het" "Гетероатомы"
        "Spec" "Зеркальный"
        "Shad" "Тени"
        "Stereo" "Стерео"
        "Label" "Подписи"
        "Settings" "Настройки"
        "POff" "Отключить выбор"
        "PIdent" "Идентифицировать"
        "PDist" "Расстояние"
        "PMon" "Монитор"
        "PAng" "Угол"
        "PTrsn" "Торсионный угол"
        "PLabl" "Подпись"
        "PCent" "Центр"
        "PCoord" "Координаты"
        "PBond" "Связь"
        "RBond" "Вращать связь"
        "RMol" "Вращать молекулу"
        "RAll" "Вращать все"
        "Export" "Экспорт"
        "Help" "Помощь"
        "About" "О программе RasMol..."
        "UserM" "Руководство пользователя..."
    }
    "SimplifiedChinese" {
        "File" "文件"
        "Open" "打开"
        "Info" "信息"
        "Close" "关闭"
        "Exit" "退出"
        "Display" "展示"
        "Wireframe" "线框"
        "Backbone" "脊梁"
        "Sticks" "枝条"
        "Spacefill" "空间填充"
        "BallStick" "球形和枝状"
        "Ribbons" "系带"
        "Strands" "纤维"
        "Cartoons" "草图"
        "MolSurf" "分子表面"
        "Colours" "颜色"
        "Monochrome" "单色"
        "CPK" "CPK"
        "Shapely" "曲线"
        "Group" "群"
        "Chain" "链"
        "Temp" "温度"
        "Struct" "结构"
        "User" "用户"
        "Model" "模型"
        "Alt" "选择"
        "Options" "附件"
        "Slab" "平板模式"
        "Hydr" "氢"
        "Het" "异种原子"
        "Spec" "镜面"
        "Shad" "影子"
        "Stereo" "立体声"
        "Label" "标签"
        "Settings" "设置"
        "POff" "选择"
        "PIdent" "鉴别"
        "PDist" "选择距离"
        "PMon" "选择监视器"
        "PAng" "选择角度"
        "PTrsn" "选择转矩"
        "PLabl" "选择标签"
        "PCent" "选择中心"
        "PCoord" "选择坐标"
        "PBond" "选择化学键"
        "RBond" "化学键轮换"
        "RMol" "摩尔轮换"
        "RAll" "全部轮换"
        "Export" "输出"
        "Help" "帮助"
        "About" "关于 RasMol..."
        "UserM" "用户手册..."
    }
    "Spanish" {
        "File" "Archivo"
        "Open" "Abrir..."
        "Info" "Información"
        "Close" "Cerrar"
        "Exit" "Quitar"
        "Display" "Mostrar"
        "Wireframe" "Alambre"
        "Backbone" "Esqueleto"
        "Sticks" "Bastones"
        "Spacefill" "Espacio Completo"
        "BallStick" "Bolas  Bastones"
        "Ribbons" "Cintas"
        "Strands" "Hebras"
        "Cartoons" "Dibujo"
        "MolSurf" "Superficie Molecular"
        "Colours" "Colores"
        "Monochrome" "Monocromo"
        "CPK" "CPK"
        "Shapely" "Forma"
        "Group" "Grupo"
        "Chain" "Cadena"
        "Temp" "Temperatura"
        "Struct" "Estructura"
        "User" "Usuario"
        "Model" "Modelo"
        "Alt" "Alt"
        "Options" "Opciones"
        "Slab" "Modo Aserrado"
        "Hydr" "Hidrógenos"
        "Het" "Heteroátomos"
        "Spec" "Especular"
        "Shad" "Sombras"
        "Stereo" "Estereo"
        "Label" "Etiquetas"
        "Settings" "Configuraciones"
        "POff" "Desactivar elección"
        "PIdent" "Elegir identificación"
        "PDist" "Elegir distancia"
        "PMon" "Elegir monitor"
        "PAng" "Elegir ángulo"
        "PTrsn" "Elegir torsiones"
        "PLabl" "Elegir etiqueta"
        "PCent" "Elegir centro"
        "PCoord" "Elegir coordenadas"
        "PBond" "Elegir enlace"
        "RBond" "Girar enlace"
        "RMol" "Girar molécula"
        "RAll" "Girar todo"
        "Export" "Exportar"
        "Help" "Ayuda"
        "About" "Acerca del RasMol..."
        "UserM" "Manual del Usuario..."
    }
    "TraditionalChinese" {
        "File" "檔案"
        "Open" "開啟"
        "Info" "資訊"
        "Close" "關閉"
        "Exit" "離開"
        "Display" "展示"
        "Wireframe" "線框"
        "Backbone" "主鏈"
        "Sticks" "棒狀"
        "Spacefill" "空間填充"
        "BallStick" "球棍模型"
        "Ribbons" "絲帶"
        "Strands" "纖維"
        "Cartoons" "卡通"
        "MolSurf" "分子表面"
        "Colours" "顏色"
        "Monochrome" "單色"
        "CPK" "CPK"
        "Shapely" "外型"
        "Group" "群組"
        "Chain" "鏈"
        "Temp" "溫度"
        "Struct" "結構"
        "User" "使用者"
        "Model" "模型"
        "Alt" "選取"
        "Options" "選項"
        "Slab" "切片模式"
        "Hydr" "氫"
        "Het" "雜原子"
        "Spec" "鏡面"
        "Shad" "陰影"
        "Stereo" "立體"
        "Label" "標籤"
        "Settings" "設定"
        "POff" "關閉選取"
        "PIdent" "識別"
        "PDist" "選取距離"
        "PMon" "監測"
        "PAng" "選取角度"
        "PTrsn" "選取扭角"
        "PLabl" "選取標籤"
        "PCent" "選取中心"
        "PCoord" "選取座標"
        "PBond" "選取化學鍵"
        "RBond" "化學鍵旋轉"
        "RMol" "分子旋轉"
        "RAll" "全部旋轉"
        "Export" "輸出"
        "Help" "說明"
        "About" "關於 RasMol"
        "UserM" "使用者手冊"
    }
}

proc tr {key} {
    global ui_translations current_ui_lang
    if {[info exists ui_translations($current_ui_lang)]} {
        foreach {k v} $ui_translations($current_ui_lang) {
            if {$k eq $key} { return $v }
        }
    }
    if {[info exists ui_translations(English)]} {
        foreach {k v} $ui_translations(English) {
            if {$k eq $key} { return $v }
        }
    }
    return $key
}

proc localize_ui {} {
    # Original menus indices: File(0), Display(1), Colours(2), Export(3), Options(4), Settings(5), Language(6), Help(7)

    set labels {
        0 "File" 1 "Display" 2 "Colours" 3 "Export" 4 "Options" 5 "Settings" 7 "Help"
    }
    foreach {idx key} $labels {
        catch { .menubar entryconfigure $idx -label [tr $key] }
    }

    # Localize "Language" menu itself
    set lang_label "Language"
    if {$::current_ui_lang eq "SimplifiedChinese"} { set lang_label "语言" }
    if {$::current_ui_lang eq "TraditionalChinese"} { set lang_label "語言" }
    if {$::current_ui_lang eq "French"} { set lang_label "Langue" }
    if {$::current_ui_lang eq "Spanish"} { set lang_label "Idioma" }
    if {$::current_ui_lang eq "Italian"} { set lang_label "Lingua" }
    if {$::current_ui_lang eq "Japanese"} { set lang_label "言語" }
    if {$::current_ui_lang eq "Russian"} { set lang_label "Язык" }
    if {$::current_ui_lang eq "Bulgarian"} { set lang_label "Език" }
    catch { .menubar entryconfigure 6 -label $lang_label }

    # File Menu
    catch { .menubar.file entryconfigure 0 -label "[tr "Open"]..." }
    catch { .menubar.file entryconfigure 1 -label [tr "Info"] }
    catch { .menubar.file entryconfigure 3 -label [tr "Close"] }
    catch { .menubar.file entryconfigure 5 -label [tr "Exit"] }

    # Display Menu
    set i 0
    foreach key {Wireframe Backbone Sticks Spacefill BallStick Ribbons Strands Cartoons MolSurf} {
        catch { .menubar.display entryconfigure $i -label [tr $key] }
        incr i
    }

    # Colours Menu
    set i 0
    foreach key {Monochrome CPK Shapely Group Chain Temp Struct User Model Alt} {
        catch { .menubar.colours entryconfigure $i -label [tr $key] }
        incr i
    }

    # Options Menu
    catch { .menubar.options entryconfigure 0 -label [tr "Slab"] }
    catch { .menubar.options entryconfigure 1 -label [tr "Hydr"] }
    catch { .menubar.options entryconfigure 2 -label [tr "Het"] }
    catch { .menubar.options entryconfigure 4 -label [tr "Spec"] }
    catch { .menubar.options entryconfigure 5 -label [tr "Shad"] }
    catch { .menubar.options entryconfigure 6 -label [tr "Stereo"] }
    catch { .menubar.options entryconfigure 7 -label [tr "Label"] }

    # Settings Menu
    set i 0
    foreach key {POff PIdent PDist PMon PAng PTrsn PLabl PCent PCoord PBond} {
        catch { .menubar.settings entryconfigure $i -label [tr $key] }
        incr i
    }
    set i 11
    foreach key {RBond RMol RAll} {
        catch { .menubar.settings entryconfigure $i -label [tr $key] }
        incr i
    }

    # Help Menu
    catch { .menubar.help entryconfigure 0 -label [tr "About"] }
    catch { .menubar.help entryconfigure 1 -label [tr "UserM"] }
}
