name: CMake on multiple platforms

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]
        c_compiler: [gcc, clang, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++
          - os: ubuntu-latest
            c_compiler: clang
            cpp_compiler: clang++
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: ubuntu-latest
            c_compiler: cl

    steps:
    - uses: actions/checkout@v4
    - name: Free Disk Space (Windows)
      if: runner.os == 'Windows'
      run: |
        rm -rf "C:/Program Files/Android"
        rm -rf "C:/android"
        rm -rf "C:/Program Files/LLVM"
        rm -rf "C:/msys64"
        rm -rf "C:/Program Files/Docker"
        rm -rf "C:/Program Files/PostgreSQL"
        rm -rf "C:/Program Files/MongoDB"
        rm -rf "C:/Program Files/MySQL"
        rm -rf "C:/Program Files/dotnet"
        rm -rf "C:/Program Files/Google"
        rm -rf "C:/Program Files/Microsoft SDKs"
        rm -rf "C:/vcpkg/downloads"
        rm -rf "C:/vcpkg/buildtrees"
      shell: bash


    - name: Install Dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev libxext-dev libxi-dev libcbf-dev libcneartree-dev libcqrlib-dev libcvector-dev libhdf5-dev tcl-dev tk-dev libdeflate-dev libjbig-dev liblerc-dev libwebp-dev libjpeg-dev libxpm-dev bison

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
        -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -DRASMOL_SKIP_HEAVY_SOURCE_BUILD=ON
        -S ${{ github.workspace }}

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Test
      working-directory: ${{ steps.strings.outputs.build-output-dir }}
      run: ctest --build-config ${{ matrix.build_type }}
